### ISSUE TITLE
"Качать на все бабки"

### ISSUE THREAD

**Issue by Yakim3396** [Solant/polygon-launcher#1]
Нужна галочка "Качать на все бабки", ну или типа "Full speed download" которая будет увеличивать количество потоков скачки и загружать всю ширину канала.
Состояние галочки учитывается только до начала обновления, так по идее проще должно быть.
Расположение прямо под кнопкой обновления, можно сдвинуть ниже соц. кнопки.

**Comment by Solant** [comment]
добавил в версии 1.2.0 ограничение в число потоков (вместо 5), должно теперь работать нормально с гиперпнями и с процессорами
