### ISSUE TITLE
Question regarding FramelessWindowHint

### ISSUE THREAD

**Issue by jswhisperer** [Solant/polygon-launcher#15]
Thank you for making this open source the dragging code was super useful. I noticed when I hide the window frame and then drag it was jumping quite a bit on the Y axis, so I opened GIMP to check my hypothesis I measured the titlebar that is now hidden and it was 39 pixels with my theme in Ubuntu. 

My question is obviously this will be a different measurment each os and maybe each user theme, is it possible to check or just live with it jumping a bit?

**Comment by Solant** [comment]
Probably window manager doesn't report proper frame size to the application, as I remember something similar was with KDE Plasma

I haven't tried to solve it yet, but you can try playing around with different window geometry properties with the frame itself, so this jiggle can be programmatically detected and removed https://doc.qt.io/qt-5/application-windows.html#window-geometry
