### ISSUE TITLE
Кнопка-иконка Discord

### ISSUE THREAD

**Issue by Yakim3396** [Solant/polygon-launcher#2]
Было бы неплохо добавить иконку ссылающуюся на наш дискорд канал, на подобие иконки телеги или вк.
Иконка - [тык](https://discordapp.com/assets/2c21aeda16de354ba5334551a883b481.png)
Инвайт-ссылка https://discordapp.com/invite/tc9ayWK
Расположение примерно между телегой и вк, а там как тебе удобнее/покажется красивее.

**Comment by Solant** [comment]
Добавил в #5
